Домашка 3 задача 1
MikePuzanov/Homework pull request #1
Opened 2020-10-03 14:41 UTC by MikePuzanov

2020-10-04 12:46 UTC, yurii-litvinov requested changes
В системы контроля версий никогда не надо выкладыввать локальные настройки и результаты сборки (для этого и есть файл .gitignore, который GitHub предлагает добавить во вновь создаваемый репозиторий всегда). Надо убрать папки .vs (она, кстати, скрытая, так что может потребоваться включить отображение скрытых папок) и Debug, и файл Задача 1.vcxproj.user (это тоже локальные настройки). Чтобы убрать, надо удалить их средствами git (git rm или его аналог в графическом клиенте), закоммитить и запушить. И настроить .gitignore после этого (можно взять отсюда https://github.com/github/gitignore VisualStudio.gitignore, переименовать его в просто .gitignore и положить в корень репозитория). Ещё стоит всегда, когда делаете пуллреквест, смотреть, что именно поменялось (это показыввается на странице создания пуллреквеста снизу), и если выкладывается что-то, что Вы не хотели выкладывать, пуллреквест не делать, а внести исправления.

Ещё, кстати, не стоит использовать русские буквы и пробелы в именах папок и файлов. Это существенно усложнит жизнь, когда вы будете, как нормальные люди, собирать всё из консоли, да ещё и под Linux-ом.

Пока 2 из 3 балла за 1-ю и 1 из 2 за 4-ю.

2020-10-04 12:46 UTC, yurii-litvinov commented on домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c
> +    add = *first;
`int add = *first;`. И почему add? Сложить? Что сложить? :)

2020-10-04 12:46 UTC, yurii-litvinov commented on домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c
> +    int p = 0;
p не подходит как имя переменной

2020-10-04 12:46 UTC, yurii-litvinov commented on домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c
> +        p = partition(array, low, high);
Эм, а  если это условие не выполнено, то норм, запускаем кусорт от нуля?

2020-10-04 12:46 UTC, yurii-litvinov commented on домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c
> +    return true;
```c
return compare(array, 8);
```

2020-10-04 12:46 UTC, yurii-litvinov commented on домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c
> +    printf("Тест пройден!\n");
Нууу, угадайте, что будет, если тест не пройдёт :)

2020-10-04 12:46 UTC, yurii-litvinov commented on домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c
> +    }
Тут тоже. Ввод некорректных данных! Отлично! Продолжим исполнение и даже не попросим ввести их заново :)

2020-10-04 13:57 UTC, MikePuzanov commented
https://github.com/MikePuzanov/Homework/pull/1  (исправления в 1 задаче, посмотрите еще раз, пожалуйста, постарался убрать недочеты)

https://github.com/MikePuzanov/Homework/pull/2  ( пулл реквест на вторую задачу из домашка 3)

https://github.com/MikePuzanov/Homework/pull/3  (пулл реквест на третью задачу из домашка 3, смотреть папку  hw3Task3 ) 
 
 
 
 
 
--
Михаил Пузанов
 
  
>Воскресенье, 4 октября 2020, 15:47 +03:00 от Yurii Litvinov <notifications@github.com>:
> 
> 
>@yurii-litvinov requested changes on this pull request.
>В системы контроля версий никогда не надо выкладыввать локальные настройки и результаты сборки (для этого и есть файл .gitignore, который GitHub предлагает добавить во вновь создаваемый репозиторий всегда). Надо убрать папки .vs (она, кстати, скрытая, так что может потребоваться включить отображение скрытых папок) и Debug, и файл Задача 1.vcxproj.user (это тоже локальные настройки). Чтобы убрать, надо удалить их средствами git (git rm или его аналог в графическом клиенте), закоммитить и запушить. И настроить .gitignore после этого (можно взять отсюда  https://github.com/github/gitignore VisualStudio.gitignore, переименовать его в просто .gitignore и положить в корень репозитория). Ещё стоит всегда, когда делаете пуллреквест, смотреть, что именно поменялось (это показыввается на странице создания пуллреквеста снизу), и если выкладывается что-то, что Вы не хотели выкладывать, пуллреквест не делать, а внести исправления.
>Ещё, кстати, не стоит использовать русские буквы и пробелы в именах папок и файлов. Это существенно усложнит жизнь, когда вы будете, как нормальные люди, собирать всё из консоли, да ещё и под Linux-ом.
>Пока 2 из 3 балла за 1-ю и 1 из 2 за 4-ю.
>----------------------------------------------------------------------
>In  домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c :
>> +    int add = 0;
>+    add = *first;
>
>int add = *first;. И почему add? Сложить? Что сложить? :)
>----------------------------------------------------------------------
>In  домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c :
>> +        }
>+    }
>+}
>+
>+void quickSort(int array[], int low, int high)
>+{
>+    if ((high - low) < 1) 
>+    {
>+        return 0;
>+    }
>+    if ((high - low + 1) < 10)
>+    {
>+        insertionSort(array, low, high);
>+        return 0;
>+    }
>+    int p = 0;
>
>p не подходит как имя переменной
>----------------------------------------------------------------------
>In  домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c :
>> +
>+void quickSort(int array[], int low, int high)
>+{
>+    if ((high - low) < 1) 
>+    {
>+        return 0;
>+    }
>+    if ((high - low + 1) < 10)
>+    {
>+        insertionSort(array, low, high);
>+        return 0;
>+    }
>+    int p = 0;
>+    if (low < high)
>+    {
>+        p = partition(array, low, high);
>
>Эм, а если это условие не выполнено, то норм, запускаем кусорт от нуля?
>----------------------------------------------------------------------
>In  домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c :
>> +    if (!compare(array, 8))
>+    {
>+        return false;
>+    }
>+    return true;
>
>return compare(array, 8);
>----------------------------------------------------------------------
>In  домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c :
>> +    if (!test())
>+    {
>+        printf("Тест не пройден!");
>+    }
>+    printf("Тест пройден!\n");
>
>Нууу, угадайте, что будет, если тест не пройдёт :)
>----------------------------------------------------------------------
>In  домашка 3 задача 1/Задача 1/Задача 1/Задача 1.c :
>> +int main()
>+{
>+    setlocale(LC_ALL, "Rus");
>+    if (!test())
>+    {
>+        printf("Тест не пройден!");
>+    }
>+    printf("Тест пройден!\n");
>+    int array[100] = {0};
>+    int size = 0;
>+    printf("Введите данные: ");
>+    scanf("%i", &size);
>+    if (size < 1)
>+    {
>+        printf("Ввод некорректных данных!");
>+    }
>
>Тут тоже. Ввод некорректных данных! Отлично! Продолжим исполнение и даже не попросим ввести их заново :)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 

2020-10-04 16:02 UTC, yurii-litvinov requested changes
Не помогло, например, всё ещё hw3Task1/Задача 1/Debug/vc142.idb в пуллреквесте. В мастере тоже куча мусора, надо почистить.

2020-10-04 17:54 UTC, MikePuzanov commented
Почистил master и hw3Task1

2020-10-05 10:20 UTC, yurii-litvinov requested changes
Пока 2.5 из 3 за эту задачу и всё и всё ещё 1 из 2 за 4-ю, .gitignore так и не появился.

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.vcxproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
Файл .user остался, и здесь, и в мастере.

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    third = *first;
Ужасно

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    int pivot = array[high];
Стоит его const-ом пометить

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +        return 0;
Функция же void, 0 ей возвращать некуда

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    int section = 0;
Ужааасно :) На самом деле, та же проблема: Вы думаете, что переменная --- это что-то вроде ящика для значений, который надо сначала куда-то поставить, а потом уже складывать туда значения. На самом деле, переменная --- это просто удобное имя для значения, так что без значения она просто не имеет смысла. Некоторые языки под "переменные" даже память не выделяют.

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +bool compare(int array[],int size)
Тут пробела после запятой не хватает

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    int size = 0;
Нигде не используется

2020-10-05 10:20 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    printf("Введите данные: ");
Какие данные? Номер банковской карты? :)

2020-10-05 14:12 UTC, yurii-litvinov requested changes

2020-10-05 14:12 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    additional = *firstElement;
Но лучше-то не стало. Я ведь хотел int additional = *firstElement;

2020-10-05 14:12 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    if ((high - low) >= 1)
```c
if (high - low < 1) {
    return;
}
...
```
Так вся суть вычислений не будет внутри скобок, так что программу будет легче читать и отлаживать

2020-10-05 14:12 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +        if (low < high)
А это разве не гарантирует условие выше?

2020-10-05 14:12 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +            quickSort(array, partition(array, low, high) + 1, high);
А зачем partition четырежды считать? Это же сразу вчетверо увеличивает время работы. Было же нормально :)

2020-10-05 17:48 UTC, yurii-litvinov approved these changes
Почти всё ок, но количество попыток исправления уже исчерпано. Итого 2.75 балла.

2020-10-05 17:48 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    int partitionForQsort = partition(array, low, high);
Вообще, она тоже могла бы быть const

2020-10-05 17:48 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    if (partitionForQsort < 10)
Мм, а при чём тут 10? Если мы сортируем кусок массива от 95-го до 100-го элемента, это условие не сможет быть выполнено и мы так и будем сортировать кусортом до самого конца

2020-10-05 17:48 UTC, yurii-litvinov commented on hw3Task1/Задача 1/Задача 1.c
> +    if (high - partitionForQsort < 10)
А вот тут правильно

2020-10-10 14:33 UTC, merged